"""Typed, lazy access to Flexi's reusable interface components.

Every leaf module remains a supported deep-import path. The facade adds a
single discoverable namespace while keeping package import itself free of
Textual and Rich initialization. The two leaf-level ``FULL`` glyphs are named
semantically here so import order can never decide which one a caller receives.
"""

from __future__ import annotations

# These imports describe attributes that PEP 562 resolves lazily at runtime.
# ruff: noqa: TC004
from types import MappingProxyType
from typing import TYPE_CHECKING, Final

if TYPE_CHECKING:
    from flexi.components import (
        allowance,
        charts,
        chrome,
        common,
        expandable,
        jump_overlay,
        jumper,
        modules,
        progress,
        punch,
        splash,
        wordmark,
        yearcalendar,
    )
    from flexi.components.allowance import (
        TOIL_SCALE,
        pace_tone,
        paint_allowance,
        paint_balance,
        paint_entitlement,
        paint_tally,
    )
    from flexi.components.charts import (
        BASELINE,
        BLOCK,
        DIVERGING_STEPS,
        EMPTY,
        HEAT,
        Burndown,
        Column,
        DivergingBars,
        WeekRibbon,
        YearHeatmap,
        week_columns,
    )
    from flexi.components.charts import FULL as CHART_FULL_GLYPH
    from flexi.components.chrome import (
        NAV_BY_SCREEN,
        NAV_ITEMS,
        OVERFLOW_TEMPLATE,
        AppFooter,
        AppHeader,
        KeyStrip,
        Lockup,
        NavBar,
        NavItem,
        NavItemLabel,
        OverflowLabel,
        StatusBar,
        StripEntry,
        footer_key_cost,
        keys_that_fit,
        strip_entries,
    )
    from flexi.components.common import (
        ALL_TONE_CLASSES,
        GAUGE_TONE_STYLES,
        MARKER,
        MIN_GAUGE_WIDTH,
        NARROW_COLUMNS,
        TINY_COLUMNS,
        TONE_CLASSES,
        TRACK,
        EmptyIndicator,
        Gauge,
        KeyHint,
        Pill,
        Rule,
        StatCard,
        Tone,
        mark_width,
        styled_track,
    )
    from flexi.components.expandable import (
        ExpandableTable,
        Row,
        RowGroup,
        RowKind,
        row_ident,
        row_key,
    )
    from flexi.components.jump_overlay import SWALLOWED_KEYS, JumpOverlay
    from flexi.components.jumper import (
        HasFocusTarget,
        HasJumpOverlays,
        HasJumpTargets,
        Jumpable,
        Jumper,
        JumpInfo,
        Refreshable,
    )
    from flexi.components.modules import (
        BADGE_WIDTH,
        BRANCH,
        CELL_PADDING,
        COLUMNS,
        FIXED_COLUMNS,
        KIND_CLASSES,
        LAST,
        MAX_JUMP_ROWS,
        STATE_CLASSES,
        STRIP_WIDTH_FLOOR,
        TRACKED,
        WEEKS,
        BalanceModule,
        BookHere,
        BookRequested,
        ClockModule,
        DeleteHere,
        Module,
        MonthView,
        RecordsModule,
        WalletModule,
        balance,
        base,
        clock,
        lean_class,
        month_grid,
        monthview,
        records,
        totals_subtitle,
        wallet,
    )
    from flexi.components.progress import MIN_RAIL, ProgressRail, TimeProgress
    from flexi.components.punch import (
        BASE_STYLES,
        PUNCH_CLASSES,
        PunchStrip,
        StyleLookup,
        absence_tokens,
        render_strip,
    )
    from flexi.components.splash import (
        CANVAS_HEIGHT,
        CANVAS_WIDTH,
        DEPTH,
        DEPTH_SAMPLES,
        DURATION,
        EDGE_ON,
        FACE_SAMPLES,
        HOLD,
        INK,
        LETTER_GLYPHS,
        LIGHT,
        RAMP,
        ROWS,
        SCALE,
        SPIN,
        STRAPLINE,
        STRAPLINE_IN,
        TILT,
        TRACKING,
        TURNS,
        VIEWER,
        WORD,
        cells,
        ease_out,
        extent,
        is_finished,
        luminance,
        pitch,
        settled_rows,
        should_play,
        strapline_fade,
        surface,
        yaw,
    )
    from flexi.components.wordmark import (
        BACKGROUND,
        FRAME_SECONDS,
        Wordmark,
        blend,
        shade,
        wanted,
    )
    from flexi.components.yearcalendar import (
        AFTERNOON,
        BLANK,
        HEADING_ROW,
        HOLIDAY,
        LABELLED_CELL,
        MIN_CELL,
        MORNING,
        PORTION_GLYPH,
        SPLIT,
        TITLE_ROW,
        TOKEN,
        YearCalendar,
        legend,
        units_column,
    )
    from flexi.components.yearcalendar import FULL as FULL_DAY_GLYPH

_MODULE_PATHS: Final = MappingProxyType(
    {
        "allowance": "flexi.components.allowance",
        "charts": "flexi.components.charts",
        "chrome": "flexi.components.chrome",
        "common": "flexi.components.common",
        "expandable": "flexi.components.expandable",
        "jump_overlay": "flexi.components.jump_overlay",
        "jumper": "flexi.components.jumper",
        "progress": "flexi.components.progress",
        "punch": "flexi.components.punch",
        "splash": "flexi.components.splash",
        "wordmark": "flexi.components.wordmark",
        "yearcalendar": "flexi.components.yearcalendar",
        "modules": "flexi.components.modules",
        "balance": "flexi.components.modules.balance",
        "base": "flexi.components.modules.base",
        "clock": "flexi.components.modules.clock",
        "monthview": "flexi.components.modules.monthview",
        "records": "flexi.components.modules.records",
        "wallet": "flexi.components.modules.wallet",
    }
)

_EXPORT_GROUPS: Final = MappingProxyType(
    {
        "flexi.components.allowance": (
            "TOIL_SCALE",
            "pace_tone",
            "paint_allowance",
            "paint_balance",
            "paint_entitlement",
            "paint_tally",
        ),
        "flexi.components.charts": (
            "BASELINE",
            "BLOCK",
            "DIVERGING_STEPS",
            "EMPTY",
            "HEAT",
            "Burndown",
            "Column",
            "DivergingBars",
            "WeekRibbon",
            "YearHeatmap",
            "week_columns",
        ),
        "flexi.components.chrome": (
            "NAV_BY_SCREEN",
            "NAV_ITEMS",
            "OVERFLOW_TEMPLATE",
            "AppFooter",
            "AppHeader",
            "KeyStrip",
            "Lockup",
            "NavBar",
            "NavItem",
            "NavItemLabel",
            "OverflowLabel",
            "StatusBar",
            "StripEntry",
            "footer_key_cost",
            "keys_that_fit",
            "strip_entries",
        ),
        "flexi.components.common": (
            "ALL_TONE_CLASSES",
            "GAUGE_TONE_STYLES",
            "MARKER",
            "MIN_GAUGE_WIDTH",
            "NARROW_COLUMNS",
            "TINY_COLUMNS",
            "TONE_CLASSES",
            "TRACK",
            "EmptyIndicator",
            "Gauge",
            "KeyHint",
            "Pill",
            "Rule",
            "StatCard",
            "Tone",
            "mark_width",
            "styled_track",
        ),
        "flexi.components.expandable": (
            "ExpandableTable",
            "Row",
            "RowGroup",
            "RowKind",
            "row_ident",
            "row_key",
        ),
        "flexi.components.jump_overlay": ("SWALLOWED_KEYS", "JumpOverlay"),
        "flexi.components.jumper": (
            "HasFocusTarget",
            "HasJumpOverlays",
            "HasJumpTargets",
            "JumpInfo",
            "Jumpable",
            "Jumper",
            "Refreshable",
        ),
        "flexi.components.progress": ("MIN_RAIL", "ProgressRail", "TimeProgress"),
        "flexi.components.punch": (
            "BASE_STYLES",
            "PUNCH_CLASSES",
            "PunchStrip",
            "StyleLookup",
            "absence_tokens",
            "render_strip",
        ),
        "flexi.components.splash": (
            "CANVAS_HEIGHT",
            "CANVAS_WIDTH",
            "DEPTH",
            "DEPTH_SAMPLES",
            "DURATION",
            "EDGE_ON",
            "FACE_SAMPLES",
            "HOLD",
            "INK",
            "LETTER_GLYPHS",
            "LIGHT",
            "RAMP",
            "ROWS",
            "SCALE",
            "SPIN",
            "STRAPLINE",
            "STRAPLINE_IN",
            "TILT",
            "TRACKING",
            "TURNS",
            "VIEWER",
            "WORD",
            "cells",
            "ease_out",
            "extent",
            "is_finished",
            "luminance",
            "pitch",
            "settled_rows",
            "should_play",
            "strapline_fade",
            "surface",
            "yaw",
        ),
        "flexi.components.wordmark": (
            "BACKGROUND",
            "FRAME_SECONDS",
            "Wordmark",
            "blend",
            "shade",
            "wanted",
        ),
        "flexi.components.yearcalendar": (
            "AFTERNOON",
            "BLANK",
            "HEADING_ROW",
            "HOLIDAY",
            "LABELLED_CELL",
            "MIN_CELL",
            "MORNING",
            "PORTION_GLYPH",
            "SPLIT",
            "TITLE_ROW",
            "TOKEN",
            "YearCalendar",
            "legend",
            "units_column",
        ),
        "flexi.components.modules": (
            "BADGE_WIDTH",
            "BRANCH",
            "CELL_PADDING",
            "COLUMNS",
            "FIXED_COLUMNS",
            "KIND_CLASSES",
            "LAST",
            "MAX_JUMP_ROWS",
            "STATE_CLASSES",
            "STRIP_WIDTH_FLOOR",
            "TRACKED",
            "WEEKS",
            "BalanceModule",
            "BookHere",
            "BookRequested",
            "ClockModule",
            "DeleteHere",
            "Module",
            "MonthView",
            "RecordsModule",
            "WalletModule",
            "lean_class",
            "month_grid",
            "totals_subtitle",
        ),
    }
)

_EXPORTS: Final = MappingProxyType(
    {
        public_name: (module_name, public_name)
        for module_name, public_names in _EXPORT_GROUPS.items()
        for public_name in public_names
    }
    | {
        "CHART_FULL_GLYPH": ("flexi.components.charts", "FULL"),
        "FULL_DAY_GLYPH": ("flexi.components.yearcalendar", "FULL"),
    }
)

# Keep the public surface grouped by its defining module.
__all__ = (  # noqa: RUF022
    "allowance",
    "charts",
    "chrome",
    "common",
    "expandable",
    "jump_overlay",
    "jumper",
    "progress",
    "punch",
    "splash",
    "wordmark",
    "yearcalendar",
    "modules",
    "balance",
    "base",
    "clock",
    "monthview",
    "records",
    "wallet",
    "TOIL_SCALE",
    "pace_tone",
    "paint_allowance",
    "paint_balance",
    "paint_entitlement",
    "paint_tally",
    "BASELINE",
    "BLOCK",
    "DIVERGING_STEPS",
    "EMPTY",
    "HEAT",
    "Burndown",
    "Column",
    "DivergingBars",
    "WeekRibbon",
    "YearHeatmap",
    "week_columns",
    "NAV_BY_SCREEN",
    "NAV_ITEMS",
    "OVERFLOW_TEMPLATE",
    "AppFooter",
    "AppHeader",
    "KeyStrip",
    "Lockup",
    "NavBar",
    "NavItem",
    "NavItemLabel",
    "OverflowLabel",
    "StatusBar",
    "StripEntry",
    "footer_key_cost",
    "keys_that_fit",
    "strip_entries",
    "ALL_TONE_CLASSES",
    "GAUGE_TONE_STYLES",
    "MARKER",
    "MIN_GAUGE_WIDTH",
    "NARROW_COLUMNS",
    "TINY_COLUMNS",
    "TONE_CLASSES",
    "TRACK",
    "EmptyIndicator",
    "Gauge",
    "KeyHint",
    "Pill",
    "Rule",
    "StatCard",
    "Tone",
    "mark_width",
    "styled_track",
    "ExpandableTable",
    "Row",
    "RowGroup",
    "RowKind",
    "row_ident",
    "row_key",
    "SWALLOWED_KEYS",
    "JumpOverlay",
    "HasFocusTarget",
    "HasJumpOverlays",
    "HasJumpTargets",
    "JumpInfo",
    "Jumpable",
    "Jumper",
    "Refreshable",
    "MIN_RAIL",
    "ProgressRail",
    "TimeProgress",
    "BASE_STYLES",
    "PUNCH_CLASSES",
    "PunchStrip",
    "StyleLookup",
    "absence_tokens",
    "render_strip",
    "CANVAS_HEIGHT",
    "CANVAS_WIDTH",
    "DEPTH",
    "DEPTH_SAMPLES",
    "DURATION",
    "EDGE_ON",
    "FACE_SAMPLES",
    "HOLD",
    "INK",
    "LETTER_GLYPHS",
    "LIGHT",
    "RAMP",
    "ROWS",
    "SCALE",
    "SPIN",
    "STRAPLINE",
    "STRAPLINE_IN",
    "TILT",
    "TRACKING",
    "TURNS",
    "VIEWER",
    "WORD",
    "cells",
    "ease_out",
    "extent",
    "is_finished",
    "luminance",
    "pitch",
    "settled_rows",
    "should_play",
    "strapline_fade",
    "surface",
    "yaw",
    "BACKGROUND",
    "FRAME_SECONDS",
    "Wordmark",
    "blend",
    "shade",
    "wanted",
    "AFTERNOON",
    "BLANK",
    "HEADING_ROW",
    "HOLIDAY",
    "LABELLED_CELL",
    "MIN_CELL",
    "MORNING",
    "PORTION_GLYPH",
    "SPLIT",
    "TITLE_ROW",
    "TOKEN",
    "YearCalendar",
    "legend",
    "units_column",
    "BADGE_WIDTH",
    "BRANCH",
    "CELL_PADDING",
    "COLUMNS",
    "FIXED_COLUMNS",
    "KIND_CLASSES",
    "LAST",
    "MAX_JUMP_ROWS",
    "STATE_CLASSES",
    "STRIP_WIDTH_FLOOR",
    "TRACKED",
    "WEEKS",
    "BalanceModule",
    "BookHere",
    "BookRequested",
    "ClockModule",
    "DeleteHere",
    "Module",
    "MonthView",
    "RecordsModule",
    "WalletModule",
    "lean_class",
    "month_grid",
    "totals_subtitle",
    "CHART_FULL_GLYPH",
    "FULL_DAY_GLYPH",
)


def __getattr__(name: str) -> object:
    if module_name := _MODULE_PATHS.get(name):
        source_name = None
    elif route := _EXPORTS.get(name):
        module_name, source_name = route
    else:
        msg = f"module {__name__!r} has no attribute {name!r}"
        raise AttributeError(msg)

    from importlib import import_module

    imported = import_module(module_name)
    value = imported if source_name is None else getattr(imported, source_name)
    globals()[name] = value
    return value


def __dir__() -> list[str]:
    """Include unresolved facade exports in interactive discovery."""
    return sorted(set(globals()) | set(__all__))
