"""Flexi's persistence model and database operations.

The direct facade mirrors :mod:`flexi.models.database` for callers that do not
need to name the storage backend. Existing deep imports remain valid.
"""

from __future__ import annotations

from flexi.models import database
from flexi.models.database import (
    CLOCK_EVENT_UPDATE_ERROR,
    CLOCK_EVENT_UPDATE_TRIGGER,
    DEFAULT_CONTRACTED_MINUTES,
    DEFAULT_WINDOW_END,
    DEFAULT_WINDOW_START,
    HEAD,
    MAX_BACKUPS,
    PROTECTED_PREFIX,
    ROUTINE_PREFIX,
    SETTINGS_SINGLETON_KEY,
    AbsenceDay,
    BalanceAdjustment,
    BankHolidayCache,
    Base,
    ClockEvent,
    DatabaseRevision,
    LeaveEntitlement,
    MigrationConfig,
    RevisionState,
    Settings,
    WorkSession,
    alembic_config,
    backup,
    backup_database,
    clock_event_update_trigger_sql,
    create_clock_event_update_trigger,
    create_db_engine,
    current_revision,
    database_scope,
    db,
    drop_clock_event_update_trigger,
    drop_clock_event_update_trigger_sql,
    enforce_foreign_keys,
    engine,
    get_session,
    invariants,
    migrate,
    moment,
    moment_of,
    prune_backups,
    punched,
    register_clock_event_immutability,
    run_migrations,
    snapshot,
    verify,
)

__all__ = (
    "CLOCK_EVENT_UPDATE_ERROR",
    "CLOCK_EVENT_UPDATE_TRIGGER",
    "DEFAULT_CONTRACTED_MINUTES",
    "DEFAULT_WINDOW_END",
    "DEFAULT_WINDOW_START",
    "HEAD",
    "MAX_BACKUPS",
    "PROTECTED_PREFIX",
    "ROUTINE_PREFIX",
    "SETTINGS_SINGLETON_KEY",
    "AbsenceDay",
    "BalanceAdjustment",
    "BankHolidayCache",
    "Base",
    "ClockEvent",
    "DatabaseRevision",
    "LeaveEntitlement",
    "MigrationConfig",
    "RevisionState",
    "Settings",
    "WorkSession",
    "alembic_config",
    "backup",
    "backup_database",
    "clock_event_update_trigger_sql",
    "create_clock_event_update_trigger",
    "create_db_engine",
    "current_revision",
    "database",
    "database_scope",
    "db",
    "drop_clock_event_update_trigger",
    "drop_clock_event_update_trigger_sql",
    "enforce_foreign_keys",
    "engine",
    "get_session",
    "invariants",
    "migrate",
    "moment",
    "moment_of",
    "prune_backups",
    "punched",
    "register_clock_event_immutability",
    "run_migrations",
    "snapshot",
    "verify",
)
