"""Database records, lifecycle helpers, and migration operations.

This is the stable persistence facade. The leaf modules remain available for a
narrower import, while wildcard imports expose only the names deliberately
listed here rather than SQLAlchemy, Alembic, or standard-library dependencies.
"""

from __future__ import annotations

from flexi.models.database import backup, db, engine, invariants, lease, migrate, moment
from flexi.models.database.backup import (
    PROTECTED_PREFIX,
    ROUTINE_PREFIX,
    snapshot,
    verify,
)
from flexi.models.database.db import (
    DEFAULT_CONTRACTED_MINUTES,
    DEFAULT_WINDOW_END,
    DEFAULT_WINDOW_START,
    SETTINGS_SINGLETON_KEY,
    AbsenceDay,
    BalanceAdjustment,
    BankHolidayCache,
    BankHolidayRefresh,
    Base,
    ClockEvent,
    LeaveEntitlement,
    Settings,
    WorkSession,
)
from flexi.models.database.engine import (
    create_db_engine,
    database_scope,
    enforce_foreign_keys,
    get_session,
)
from flexi.models.database.invariants import (
    CLOCK_EVENT_UPDATE_ERROR,
    CLOCK_EVENT_UPDATE_TRIGGER,
    WORK_SESSION_ACTION_INSERT_TRIGGER,
    WORK_SESSION_ACTION_UPDATE_TRIGGER,
    WORK_SESSION_CLOCK_IN_ACTION_ERROR,
    WORK_SESSION_CLOCK_OUT_ACTION_ERROR,
    clock_event_update_trigger_sql,
    create_clock_event_update_trigger,
    create_work_session_action_triggers,
    drop_clock_event_update_trigger,
    drop_clock_event_update_trigger_sql,
    drop_work_session_action_trigger_sql,
    drop_work_session_action_triggers,
    register_clock_event_immutability,
    register_work_session_action_invariants,
    work_session_action_trigger_name,
    work_session_action_trigger_sql,
)
from flexi.models.database.lease import (
    DEFAULT_LEASE_TIMEOUT,
    LEASE_POLL_INTERVAL,
    DatabaseBusyError,
    LeaseMode,
    database_lease,
    lease_path,
)
from flexi.models.database.migrate import (
    HEAD,
    MAX_BACKUPS,
    DatabaseRevision,
    MigrationConfig,
    RevisionState,
    alembic_config,
    backup_database,
    current_revision,
    prune_backups,
    run_migrations,
)
from flexi.models.database.moment import moment_of, punched

__all__ = (
    "CLOCK_EVENT_UPDATE_ERROR",
    "CLOCK_EVENT_UPDATE_TRIGGER",
    "DEFAULT_CONTRACTED_MINUTES",
    "DEFAULT_LEASE_TIMEOUT",
    "DEFAULT_WINDOW_END",
    "DEFAULT_WINDOW_START",
    "HEAD",
    "LEASE_POLL_INTERVAL",
    "MAX_BACKUPS",
    "PROTECTED_PREFIX",
    "ROUTINE_PREFIX",
    "SETTINGS_SINGLETON_KEY",
    "WORK_SESSION_ACTION_INSERT_TRIGGER",
    "WORK_SESSION_ACTION_UPDATE_TRIGGER",
    "WORK_SESSION_CLOCK_IN_ACTION_ERROR",
    "WORK_SESSION_CLOCK_OUT_ACTION_ERROR",
    "AbsenceDay",
    "BalanceAdjustment",
    "BankHolidayCache",
    "BankHolidayRefresh",
    "Base",
    "ClockEvent",
    "DatabaseBusyError",
    "DatabaseRevision",
    "LeaseMode",
    "LeaveEntitlement",
    "MigrationConfig",
    "RevisionState",
    "Settings",
    "WorkSession",
    "alembic_config",
    "backup",
    "backup_database",
    "clock_event_update_trigger_sql",
    "create_clock_event_update_trigger",
    "create_db_engine",
    "create_work_session_action_triggers",
    "current_revision",
    "database_lease",
    "database_scope",
    "db",
    "drop_clock_event_update_trigger",
    "drop_clock_event_update_trigger_sql",
    "drop_work_session_action_trigger_sql",
    "drop_work_session_action_triggers",
    "enforce_foreign_keys",
    "engine",
    "get_session",
    "invariants",
    "lease",
    "lease_path",
    "migrate",
    "moment",
    "moment_of",
    "prune_backups",
    "punched",
    "register_clock_event_immutability",
    "register_work_session_action_invariants",
    "run_migrations",
    "snapshot",
    "verify",
    "work_session_action_trigger_name",
    "work_session_action_trigger_sql",
)
