name: Build

on: [push, workflow_dispatch, workflow_call]

jobs:
  run:
    name: "Python ${{ matrix.python-version }} on ${{ matrix.os }}"

    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12", "3.13"]
        os: [ubuntu-latest, windows-latest]

    runs-on: ${{ matrix.os }}

    defaults:
      run:
        working-directory: .

    steps:
      - uses: actions/checkout@v4

      - name: Install uv ${{ matrix.python-version }}
        uses: astral-sh/setup-uv@v3
        with:
          enable-cache: true
          cache-dependency-glob: uv.lock

      - name: Set up Python
        run: uv python install ${{ matrix.python-version }}

      - name: Build
        run: uv build
