name: Tests

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    types: [opened, synchronize, reopened]
    paths:
      - ".github/workflows/tests.yaml"
      - "src/**/*.py"
      - "tests/**/*.py"
jobs:
  pytest:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install uv 3.13
        uses: astral-sh/setup-uv@v3
        with:
          enable-cache: true
          cache-dependency-glob: uv.lock

      - name: Set up Python 3.13
        run: uv python install 3.13

      - name: Run Pytest
        run: uv run pytest
